### ISSUE TITLE
questions about latent variable

### ISSUE THREAD

**Issue by xixiareone** [agupt013/ALANET#1]
I am interested in your work, can you share the code? many thanks

**Comment by agupt013** [comment]
Hi,
Thank you for your interest in our work. We are still working on further developments of the work and will release once we complete that. I'll keep the issue open till the code is uploaded. 

Let me know if you have any questions regarding the work. I'll be happy to discuss it with you.

Thanks,
Akash

**Comment by agupt013** [comment]
I added the code. This is old version of the code. Some files may be outdated. I have also attached one checkpoint for the model.
